name: .NET build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

env:
  PACKAGE_SOURCE: github

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup and cache dependencies
      uses: cybercryptio/build-setup-action@master

    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@cybercryptio'

    - name: Install NPM modules
      run: npm install

    - name: Build
      run: make build

    - name: Lint
      run: make lint

    - name: Log in to the Github container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: cybot-cc
        password: ${{ secrets.CYBOT_TOKEN }}

    - name: Test
      run: make tests

    - name: Install GitVersion
      if: github.ref_name == 'master'
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.x'

    - name: Determine Version
      if: github.ref_name == 'master'
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        additionalArguments: '/overrideconfig mode=ContinuousDeployment'

    - name: Set package version
      if: github.ref_name == 'master'
      run: npm version ${{ steps.gitversion.version }} --no-git-tag-version

    - name: Publish package
      if: github.ref_name == 'master'
      run: make publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.CYBOT_TOKEN }}

    - name: Create tag
      if: github.ref_name == 'master'
      run: |
        git tag -f v${{ steps.gitversion.outputs.semVer }}
        git push origin v${{ steps.gitversion.outputs.semVer }}
